require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Max: 20
  Exclude:
  - "**/*_test.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
  - "**/*_test.rb"

Metrics/ModuleLength:
  Exclude:
  - "**/*_test.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
