AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

# Offense count: 624
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 231

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 101

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 11

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 30

# Offense count: 286
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: Strict, AllowedNumbers.
Style/NumericLiterals:
  MinDigits: 11

# Offense count: 538
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 326

Lint/EmptyBlock:
  Enabled: false
