name: reviewdog
on: [pull_request]
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          rubocop_flags: --fail-level=warning
          rubocop_version: gemfile
          rubocop_extensions: rubocop-performance:gemfile rubocop-minitest:gemfile

  rubocop-all:
    name: runner / rubocop-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          level: warning
          reporter: github-pr-review # Default is github-pr-check
          rubocop_flags: --fail-level=warning
          rubocop_version: gemfile
          rubocop_extensions: rubocop-performance:gemfile rubocop-minitest:gemfile
